### PR TITLE
Add ApiError comments (closes #107)

### LINKED ISSUE #107: Fix incorrect docs for ApiError subclasses

### PR DESCRIPTION
**Pull request by floriandejonckheere**

### CODE REVIEW

**Comment by floriandejonckheere** [comment]
You want to make a clear distinction between backend and frontend errors? Then we have to rename _all_ error classes. For instance, `ObjectNotFoundError` does not make it clear exactly where this comes from either.

**Comment by Dromin** [comment]
Not necessarily between backend and frontend errors; I just want to be able to tell at first glance *what exactly* the type of problem is. `ValidationError` doesn't tell me that. Is it a function argument that doesn't validate? A form field? An api call? Who knows? Same with `ForbiddenError`. Did I try to access a page that is forbidden? Did I try to post values that are forbidden? No way to tell. If 'forbidden' refers to an HTTP status, it should be called `HttpStatusForbiddenError` or something like that, imo.

**Comment by floriandejonckheere** [comment]
That's what the error hierarchy is for. I don't want to have the Java convention of putting everything in the class names, that makes it unnecessarily long and complex.
It's also usually a combination of multiple factors. `ValidationErrors` are caused by invalid user values, yet emitted by the API. I'm still figuring out how best to handle the errors in the sagas.

**Comment by floriandejonckheere** [comment]
Actually, keeping class names concise yet descriptive improves the readability a lot. Nobody wants to read code where there are tons of references to `HttpStatusEmailTooShortValidationError`. This example is a bit exaggerated, but you get the point.
I'm all for improving developer happiness and efficiency, but reading these names and the accompanying cognitive duplication does not make me happy.

Basically, for every error that we can encounter, there are similar client side and server side equivalents. `NotImplementedError`, `UnsupportedOperationError`, `NotFoundError`, `InvalidArgumentError` and more. We can either rely on the inheritance mechanism to make this discrepancy clear (which is what I prefer), or suffix _every_ error with `ServerError`, `ClientError` or something similar.

@Dromin @JasperDhaene @mielvds your thoughts?

**Comment by floriandejonckheere** [comment]
> Why would you want to display a NotYetImplementedError from the backend in the frontend?

Not Implemented is a HTTP 501 status code. I'm not saying we should display these errors to the user, but they can be thrown by the API. Specifically because the API adheres to the [JSON API](http://jsonapi.org/) standard, but the library I am using in the backend does not implement every feature described in the spec.

A REST API cannot throw errors in a React app. Nevertheless the generated ones still come from the backend.
The issue of async errors is not solved yet. One of the solutions I'm thinking about is also not using any errors in `lib/api`, yet rather returning a `Response` object with the appropriate success/error response. Then the API sagas would throw errors/dispatch actions based on that response. That would deprecate the entire ApiError tree.

**Comment by Dromin** [comment]
> Not Implemented is a HTTP 501 status code. I'm not saying we should display these errors to the user, but they can be thrown by the API. Specifically because the API adheres to the JSON API standard, but the library I am using in the backend does not implement every feature described in the spec.

But see, that's my point. The frontend doesn't care what exact error was thrown in the backend, it only cares that it got back an HTTP 501 response. In response to that, it could throw an `HttpStatusNotImplementedError`, which is very obviously distinct from a `NotYetImplementedError`. When seeing these error class names, you intuitively understand that the former was caused by a problem in the backend or in communication with the backend, while the latter is situated in the frontend. If you called the former `NotImplementedError` (similar to what you've been doing with other HTTP statuses), you lose that distinction.

**Comment by floriandejonckheere** [comment]
I understand your point and I agree, but I prefer having the inheritance tree over long class names. We aren't losing any distinctions by not using more descriptive class names. It seems pretty clear to me which error we are talking about here:

screenshot253

> So perhaps we should postpone merging this branch until that has been figured out?

I will try to redesign the error flow next week, if I find some time.

**Comment by Dromin** [comment]
The problem with that is that the inheritance tree isn't always available. For example, if you're reading existing code and come across a `NotImplementedError`, you'd have to scroll all the way up to the import statements to see that it's located in the `errors/api-errors` subfolder. Same with some methods of error reporting - it's dangerous to assume that there will always be a stack trace available.

The error inheritance tree was never meant to be used this way to begin with. I made these subdivisions purely so we could, for example, group all usage errors together in a single `catch` statement, and so that different groups of errors could have different default values for translation.

**Comment by mielvds** [comment]
you guys don't work in typescript do you? Why would you want to go the Java way. Keep some general error classes and provide extra information dynamically

**Comment by floriandejonckheere** [comment]
Your IDE has support for resolving these references, without you having to scroll to the top.
In any case, `ApiError`s are only encountered in the code when writing code that concerns API interaction, and it should contextually already be clear to the developer.

Unfortunately JavaScript does not have any native support for catching specific error classes, so you'll end up using `instanceof` in your catch clause anyway.
Then why are we using specific error classes anyway? A generic developer-oriented error class with an error message and a translatable error class should do the trick.

**Comment by Dromin** [comment]
> Keep some general error classes and provide extra information dynamically

Isn't that what we're doing? Although it depends on what you'd define als a 'general' error class. But the reasons I implemented it like this are:
1. Different types of errors need to be processed differently. For example, usage errors need to be shown to the user, implementation errors should only be visible to the developer.
2. Different types of errors have different default values for translation and sometimes can autogenerate their own error message to avoid duplication. For example, `ObjectNotFoundError` can take the name of the object and the id that was not found and generate a standardized error message, which is less work for the developer and keeps things consistent.
3. It is much easier to write / read tests when you use custom errors. For example  
    ```
    expect(...).toThrow(InvalidArgumentError);
    ```  
    vs  
    ```
    expect(...).toThrow('copypasted exact error message that needs to be updated in two places every time');
    ```  
    (Note that you can't just test for a generic `Error` because in that case you might get false negatives if a piece of code throws an error in more than one situation.)

(And also, what's up with all the Java hate? lol)

**Comment by Dromin** [comment]
> Unfortunately JavaScript does not have any native support for catching specific error classes, so you'll end up using `instanceof` in your catch clause anyway.

Yes, but superclasses make the difference between:
```
catch (e: Error) {
  if (e instanceof ImplementationError) { ... }
}
```
and
```
catch (e: Error) {
  if (e instanceof CorruptedInternalStateError
    || e instanceof InvalidArgumentError 
    || ... add all other implementation errors and update every time a new error is added
  ) { ... }
}
```

**Pull request closed without merging**
